# Nginx의 Alpine 이미지를 기반으로 합니다.
FROM nginx:alpine

# Nginx의 기본 설정 파일을 삭제합니다.
RUN rm /etc/nginx/conf.d/default.conf

# 호스트의 설정 파일을 컨테이너 내부로 복사합니다.
COPY /etc/nginx/sites-available/default.conf /etc/nginx/conf.d/default.conf

# 프론트엔드 애플리케이션을 컨테이너 내부로 복사합니다.
COPY /frontend /usr/share/nginx/html

# 컨테이너에서 사용할 포트를 엽니다. 프론트엔드는 80번 포트를 사용합니다.
EXPOSE 80

# Nginx를 백그라운드에서 실행합니다.
CMD ["nginx", "-g", "daemon off;"]
