version: "3"
services:
  nginx:
    build: 
      context: ./frontend
    ports:
      - 80:80
    depends_on:
      - spring

  spring:
    build: 
      context: ./backend
    ports:
      - 8080:8080 #로컬포트:컨테이너포트
