spring:
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원여부 (default: true)
      max-file-size: 100MB
      max-request-size: 100MB
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: ${spring.kakao.client-id}
#            client-secret: ${spring.kakao.client-secret}
#            redirect-uri: "http://localhost:8080/oauth"
#            client-authentication-method: client_secret_post
#            authorization-grant-type: authorization_code
#            scope:
#              - profile_nickname
#              - profile_image
#              - account_email
#            client-name: kakao
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id

logging:
  level:
    org:
      apache:
        http: DEBUG
    httpclient:
      wire: DEBUG
kakao:
  clientId : ${spring.kakao.client-id}
  secret: ${spring.kakao.client-secret}

cloud:
  aws:
    credentials:
      access-key: ${aws.s3.accesskey}
      secret-key: ${aws.s3.secretkey}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ssafys3
