spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${spring.datasource.username}
    url: ${spring.datasource.url-mysql}
server:
  servlet:
    encoding:
      force: 'true'
      enabled: 'true'
      charset: UTF-8
    context-path: /
  port: '8080'